// src/content/actualites/article-content.ts

// ─── Helper ──────────────────────────────────────────────
const img = (caption: string, id: string) =>
  `![${caption}](https://images.unsplash.com/${id}?w=900&auto=format&fit=crop&q=80)`

// ─── 1. SYSCOHADA révisé ─────────────────────────────────
export const ARTICLE_CONTENT_SYSCOHADA: string[] = [
  "## Contexte de la révision",
  "Le SYSCOHADA révisé, entré en vigueur le 1er janvier 2018, continue d'évoluer. Les ajustements apportés en 2024 visent à rapprocher davantage le référentiel OHADA des normes IFRS, tout en préservant les spécificités du contexte africain.",
  "Ces modifications ne sont pas cosmétiques. Elles impactent directement la manière dont les entreprises congolaises présentent leurs états financiers, comptabilisent certaines opérations et communiquent avec leurs parties prenantes.",
  img("Les états financiers doivent désormais répondre à de nouvelles exigences de présentation", "photo-1554224155-6726b3ff858f"),
  "> Les entreprises qui n'anticipent pas ces changements s'exposent à des réserves du commissaire aux comptes et à des difficultés avec les régulateurs.",
  "La révision s'inscrit dans un mouvement continental de modernisation comptable. Plusieurs pays membres de l'OHADA ont déjà entamé des travaux d'adaptation, et la RDC ne fait pas exception. Les cabinets d'audit, les directions financières et les régulateurs sont tous concernés par cette évolution majeure.",
  "## Les principales modifications à connaître",
  "### 1. Présentation des états financiers",
  "Le format du bilan et du compte de résultat a été ajusté pour améliorer la lisibilité et la comparabilité. Les entreprises doivent désormais présenter séparément certains éléments qui étaient auparavant agrégés.",
  "- Séparation obligatoire des activités ordinaires et des éléments HAO\n- Nouveau format du tableau des flux de trésorerie\n- Notes annexes renforcées avec davantage d'informations qualitatives\n- Présentation obligatoire des engagements hors bilan",
  "Cette évolution vise à aligner la pratique congolaise sur les standards internationaux. Les investisseurs et les partenaires financiers pourront désormais comparer plus facilement les performances des entreprises de différents pays OHADA.",
  "### 2. Contrats de location",
  "L'une des modifications les plus significatives concerne le traitement comptable des contrats de location. Inspiré de la norme IFRS 16, le nouveau traitement impose aux preneurs de reconnaître un actif et un passif pour la quasi-totalité des contrats de location.",
  img("La nouvelle norme sur les contrats de location impacte directement le bilan des entreprises", "photo-1460925895917-afdab827c52f"),
  "Concrètement, cela signifie que les loyers qui apparaissaient uniquement en charges au compte de résultat vont désormais générer un actif au bilan (le droit d'utilisation) et une dette (l'obligation de paiement des loyers futurs).",
  "> Pour les entreprises ayant des baux immobiliers ou des contrats de location de matériel significatifs, l'impact sur le bilan peut être considérable.",
  "Les entreprises minières et les banques seront particulièrement touchées. En effet, de nombreuses sociétés minières louent des engins lourds, des véhicules et des bâtiments sur de longues durées. Le passage de ces contrats au bilan va modifier significativement leurs ratios financiers.",
  "### 3. Instruments financiers",
  "Le traitement des instruments financiers a été aligné sur les principes de l'IFRS 9, avec des simplifications adaptées au contexte OHADA. Les principales nouveautés concernent la classification et l'évaluation des actifs financiers, ainsi que le modèle de dépréciation basé sur les pertes de crédit attendues.",
  "- Trois catégories de classification des actifs financiers\n- Modèle de dépréciation prospectif (pertes attendues)\n- Comptabilité de couverture simplifiée\n- Informations à fournir en annexe renforcées",
  "## Impact pour les entreprises congolaises",
  "### Sociétés minières",
  "Les sociétés minières seront particulièrement impactées par les nouvelles dispositions sur les contrats de location (engins, véhicules, bâtiments) et sur les provisions pour réhabilitation de sites. La documentation requise sera significativement plus importante.",
  img("Le secteur minier congolais fait face à des exigences comptables de plus en plus strictes", "photo-1504328345606-18bbc8c9d7d1"),
  "Les entreprises du secteur devront également revoir leur politique de comptabilisation des coûts d'exploration et de développement. La distinction entre ces deux phases, déjà délicate en pratique, devra être documentée de manière plus rigoureuse.",
  "### Établissements bancaires",
  "Les banques devront adapter leur modèle de provisionnement des créances pour intégrer l'approche par les pertes de crédit attendues. Cela nécessitera des outils de modélisation et une collaboration étroite entre les équipes risques et comptabilité.",
  "L'impact sera particulièrement sensible sur le portefeuille de prêts aux entreprises. Les banques devront non seulement provisionner les créances en souffrance, mais également anticiper les pertes futures sur l'ensemble de leur portefeuille, y compris les prêts encore performants.",
  "### PME et ETI",
  "Pour les entreprises de taille moyenne, l'impact principal sera sur les contrats de location et la présentation des états financiers. Un accompagnement par un expert-comptable est fortement recommandé pour la première application.",
  "> Les PME qui tardent à se préparer risquent de se retrouver en difficulté lors de la première clôture appliquant les nouvelles dispositions. Le temps de la mise en conformité est souvent sous-estimé.",
  "## Comment se préparer",
  "La préparation est la clé d'une transition réussie. Voici les étapes recommandées par nos équipes pour accompagner votre entreprise dans cette démarche :",
  "- Réaliser un diagnostic d'impact avec votre cabinet comptable\n- Identifier les contrats de location significatifs et estimer l'impact bilanciel\n- Mettre à jour le paramétrage de votre logiciel comptable\n- Former vos équipes comptables aux nouvelles dispositions\n- Planifier la communication avec votre commissaire aux comptes",
  img("La formation des équipes est un facteur clé de réussite de la transition", "photo-1552664730-d307ca884978"),
  "## Notre accompagnement",
  "Chez CAAF SAS, nous accompagnons déjà plusieurs entreprises congolaises dans la préparation de cette transition. Notre approche combine un diagnostic d'impact personnalisé, la mise à jour des procédures comptables et la formation de vos équipes.",
  "Nous avons développé une méthodologie éprouvée en trois phases : diagnostic initial, mise en œuvre des ajustements, et suivi post-application. Cette approche permet de sécuriser la transition tout en maintenant la continuité des opérations comptables.",
  "> N'attendez pas la clôture pour découvrir l'impact sur vos comptes. Anticipez dès maintenant pour une transition sereine.",
  "Si vous souhaitez évaluer l'impact des modifications du SYSCOHADA sur votre entreprise, nos équipes sont disponibles pour un premier échange sans engagement.",
]

// ─── 2. Contrôle fiscal RDC ──────────────────────────────
export const ARTICLE_CONTENT_CONTROLE_FISCAL: string[] = [
  "## Un contexte fiscal en pleine mutation",
  "La Direction Générale des Impôts (DGI) a considérablement intensifié ses opérations de contrôle fiscal au cours des dernières années. En 2024, le nombre de vérifications a augmenté de plus de 30% par rapport à l'exercice précédent, avec un focus particulier sur les secteurs minier, bancaire et des télécommunications.",
  "Cette dynamique s'inscrit dans la stratégie du gouvernement congolais d'élargir l'assiette fiscale et de réduire l'écart de recouvrement. Pour les entreprises, cela signifie une probabilité accrue de faire l'objet d'un contrôle — et une nécessité absolue d'être préparé.",
  img("Les documents comptables doivent être impeccables avant tout contrôle fiscal", "photo-1554224155-1696413565d3"),
  "## Les 10 points clés à vérifier",
  "### 1. La cohérence des déclarations",
  "L'erreur la plus fréquente — et la plus coûteuse — est l'incohérence entre les différentes déclarations fiscales. Les vérificateurs croisent systématiquement les déclarations de TVA, les liasses fiscales et les déclarations d'impôt sur les revenus.",
  "- Cohérence entre chiffre d'affaires déclaré TVA et chiffre d'affaires du bilan\n- Concordance des déductions entre exercices\n- Correspondance entre les charges déduites et les factures fournisseurs\n- Rapprochement des acomptes provisionnels avec le résultat final",
  "### 2. La documentation des charges",
  "Toute charge déduite doit être justifiée par une pièce probante. Les charges les plus souvent rejetées lors des contrôles sont :",
  "- Les charges de personnel sans bordereaux de paie complets\n- Les prestations de services sans contrats ni rapports de mission\n- Les frais de déplacement sans justificatifs détaillés\n- Les charges exceptionnelles sans documentation d'appui",
  img("Chaque pièce comptable doit pouvoir être retracée et justifiée", "photo-1454165804606-c3d57bc86b40"),
  "### 3. Le traitement de la TVA",
  "La TVA est le poste qui génère le plus de redressements. Les erreurs les plus courantes portent sur la déduction de la TVA sur des dépenses non déductibles, le non-reversement de la TVA déduite sur des créances irrécouvrables, et la mauvaise application du taux.",
  "> Un redressement de TVA ne se limite jamais à la taxe elle-même. Il entraîne systématiquement des pénalités de retard de 10% par mois et des majorations qui peuvent atteindre 40% du montant redressé.",
  "### 4. Les prix de transfert",
  "Pour les entreprises liées à des groupes internationaux, les opérations intragroupe font l'objet d'un examen approfondi. La DGI vérifie que les prix pratiqués correspondent à des valeurs de marché et que la documentation de prix de transfert est conforme.",
  "### 5. Les amortissements et provisions",
  "Les vérificateurs contrôlent systématiquement la politique d'amortissement (durées, taux, méthode) et le calcul des provisions. Les provisions excessives ou insuffisamment documentées sont fréquemment rejetées.",
  "## Comment réagir en cas de notification",
  "La réception d'un avis de vérification ne doit pas être prise à la légère. Voici la marche à suivre recommandée par nos équipes :",
  "- Ne jamais ignorer la notification ou demander des reports intempestifs\n- Rassembler l'ensemble de la documentation comptable et fiscale\n- Désigner un interlocuteur unique pour les échanges avec la DGI\n- Faire préparer les réponses par votre cabinet comptable\n- Ne fournir que les documents expressément demandés",
  img("L'accompagnement par un expert-comptable est essentiel pendant un contrôle fiscal", "photo-1521791136064-7986c2920216"),
  "## Les pénalités à connaître",
  "Le Livre de Procédures Fiscales de la RDC prévoit un arsenal de sanctions en cas de manquement. Les principales pénalités sont : 10% du droit omis en cas de déclaration incomplète, 40% en cas de mauvaise foi, et 100% en cas de manœuvre frauduleuse. S'ajoutent des intérêts de retard de 1,5% par mois.",
  "## Prévenir plutôt que guérir",
  "La meilleure stratégie face au contrôle fiscal est la prévention. Un audit fiscal préventif permet d'identifier les risques et de les corriger avant qu'un vérificateur ne les découvre. C'est un investissement largement rentabilisé par rapport au coût d'un redressement.",
  "> Chez CAAF SAS, nous recommandons à tous nos clients de réaliser un diagnostic fiscal annuel. Ce contrôle préventif coûte infiniment moins cher qu'un redressement fiscal.",
]

// ─── 3. Audit interne PME ────────────────────────────────
export const ARTICLE_CONTENT_AUDIT_INTERNE: string[] = [
  "## L'audit interne : un luxe ? Non, une nécessité.",
  "De nombreux dirigeants de PME congolaises considèrent encore l'audit interne comme une fonction réservée aux grandes entreprises. C'est une erreur stratégique. L'audit interne est un outil de pilotage essentiel, quelle que soit la taille de l'organisation.",
  "Dans un environnement où les risques de fraude, d'erreur comptable et de non-conformité sont omniprésents, disposer d'un contrôle interne fiable n'est pas un luxe — c'est une condition de survie.",
  img("Les PME congolaises ont tout intérêt à structurer leur fonction d'audit interne", "photo-1573164713988-8665fc963095"),
  "## Pourquoi externaliser ?",
  "Pour une PME, recruter un auditeur interne à temps plein représente un coût important : salaire, formation, outils, et surtout — objectivité. Un auditeur interne salarié peut rapidement être confronté à des conflits d'intérêts ou à une pression hiérarchique qui compromettent son indépendance.",
  "L'externalisation résout ces problèmes de manière élégante. Le cabinet d'audit externe apporte une expertise spécialisée, une indépendance totale et une flexibilité dans l'allocation des ressources.",
  "- Coût maîtrisé : vous payez pour le temps d'intervention, pas pour un poste fixe\n- Indépendance garantie : aucun lien hiérarchique avec la direction\n- Expertise diversifiée : accès à des compétences multiples (finance, IT, fiscalité)\n- Benchmarks sectoriels : le cabinet peut comparer vos pratiques avec celles du marché\n- Flexibilité : l'intensité de l'intervention s'adapte à vos besoins réels",
  "## Ce qu'un audit interne externalisé couvre",
  "La mission d'audit interne externalisée couvre généralement les domaines suivants, adaptés aux priorités de chaque entreprise :",
  "### Revue des processus comptables et financiers",
  "L'auditeur examine le circuit de la facturation, les procédures de trésorerie, le rapprochement bancaire, la gestion des immobilisations et le processus de clôture mensuelle. L'objectif est de détecter les failles et de proposer des améliorations concrètes.",
  img("L'examen des processus financiers est au cœur de la mission d'audit interne", "photo-1460925895917-afdab827c52f"),
  "### Évaluation du contrôle interne",
  "L'auditeur teste les contrôles existants : séparation des fonctions, validation des dépenses, accès aux systèmes, procédures d'approbation. Il identifie les zones de risque et propose un plan d'action priorisé.",
  "### Conformité réglementaire",
  "Vérification du respect des obligations fiscales, sociales et réglementaires. Ce volet est particulièrement important en RDC, où le cadre réglementaire évolue fréquemment.",
  "> Nous recommandons une mission d'audit interne d'une durée de 2 à 4 semaines, répartie sur l'année, pour une PME de taille moyenne. Cette fréquence permet un suivi régulier sans alourdir l'organisation.",
  "## Retour sur investissement",
  "Le coût d'une mission d'audit interne externalisée est largement compensé par les économies qu'elle génère : réduction des erreurs, prévention des fraudes, optimisation des processus et amélioration de la conformité fiscale.",
  "Nos clients ayant mis en place un audit interne régulier constatent en moyenne une réduction de 25% des anomalies comptables et une amélioration significative de la fiabilité de leurs états financiers.",
]

// ─── 4. Prix de transfert ────────────────────────────────
export const ARTICLE_CONTENT_PRIX_TRANSFERT: string[] = [
  "## Qu'est-ce que les prix de transfert ?",
  "Les prix de transfert désignent les prix pratiqués entre des entreprises appartenant au même groupe lors de transactions transfrontalières. Ces opérations — vente de biens, prestations de services, redevances, prêts intragroupe — doivent être fixées à des conditions de pleine concurrence, c'est-à-dire aux mêmes conditions que si les parties avaient été indépendantes.",
  "La problématique est simple : si une entreprise congolaise vend sa production à sa maison-mère à un prix inférieur au prix du marché, elle réduit artificiellement son résultat imposable en RDC. Les autorités fiscales congolaises, comme celles de la plupart des pays, ne l'entendent pas de cette oreille.",
  img("Les transactions intragroupe font l'objet d'un contrôle fiscal accru", "photo-1486406146926-c627a92ad1ab"),
  "## Le cadre réglementaire congolais",
  "La RDC a introduit des règles de prix de transfert dans sa législation fiscale, principalement inspirées des Principes de l'OCDE. L'article 26 de la Loi n° 004/2003 relative au régime fiscal des profits et plus-values de l'État donne à l'administration fiscale le pouvoir de redresser les prix de transfert ne correspondant pas aux valeurs normales.",
  "Les entreprises concernées doivent tenir une documentation de prix de transfert comprenant :",
  "- L'identification du groupe et de ses membres\n- La description des transactions intragroupe\n- L'analyse fonctionnelle des parties prenantes\n- Le choix et l'application de la méthode de prix de transfert\n- Les données financières comparatives",
  "## Les méthodes acceptées",
  "### Méthodes traditionnelles",
  "La méthode du prix comparable sur le marché libre (CUP) est la méthode privilégiée lorsqu'il existe des transactions comparables sur le marché ouvert. À défaut, la méthode du coût majoré et la méthode de revente peuvent être utilisées.",
  "### Méthodes transactionnelles",
  "La méthode de la marge nette transactionnelle (TNMM) est la plus couramment utilisée en pratique, car elle est moins exigeante en termes de données comparables. Elle consiste à comparer la marge nette réalisée par l'entreprise testée avec celle d'entreprises comparables indépendantes.",
  img("La documentation de prix de transfert doit être préparée avant toute vérification", "photo-1554224155-1696413565d3"),
  "## Les secteurs les plus exposés en RDC",
  "Certains secteurs sont particulièrement exposés au risque de redressement de prix de transfert en RDC :",
  "- Le secteur minier : vente de matières premières à des négociants ou des maisons-mères\n- Le secteur des télécommunications : redevances de marques et de technologie\n- Le secteur bancaire : financements intragroupe et commissions\n- Le secteur de la grande distribution : marges sur les achats de marchandises",
  "> La DGI dispose désormais de bases de données internationales lui permettant de comparer les prix pratiqués par les entreprises congolaises avec les standards du marché. L'argument de l'absence de comparables ne tient plus.",
  "## Les sanctions encourues",
  "En l'absence de documentation de prix de transfert, l'administration fiscale peut procéder à un redressement d'office et appliquer des pénalités pouvant atteindre 40% du montant redressé en cas de mauvaise foi. La charge de la preuve repose sur le contribuable.",
  "## Notre recommandation",
  "Nous recommandons à tout groupe ayant des transactions intragroupe avec des entités établies en RDC de préparer une documentation de prix de transfert solide, mise à jour annuellement et prête à être présentée en cas de contrôle.",
  "> Chez CAAF SAS, nous réalisons des diagnostics de prix de transfert pour les groupes internationaux opérant en RDC. Notre approche combine une analyse juridique rigoureuse et une connaissance approfondie des réalités du terrain.",
]

// ─── 5. Secteur minier ───────────────────────────────────
export const ARTICLE_CONTENT_SECTEUR_MINIER: string[] = [
  "## Un secteur stratégique sous haute surveillance",
  "Le secteur minier représente la colonne vertébrale de l'économie congolaise. Avec plus de 90% des exportations du pays, le secteur attire des investissements massifs mais aussi une attention réglementaire croissante. En 2024, les exigences d'audit et de reporting n'ont jamais été aussi élevées.",
  "Les sociétés minières opérant en RDC doivent composer avec un cadre réglementaire complexe : le Code minier révisé, les exigences ITIE (Initiative pour la Transparence dans les Industries Extractives), les normes IFRS, et les obligations spécifiques liées à leurs maisons-mères.",
  img("Le secteur minier en RDC fait face à des défis uniques en matière d'audit", "photo-1504328345606-18bbc8c9d7d1"),
  "## Les enjeux spécifiques de l'audit minier",
  "### Évaluation des réserves et ressources",
  "L'évaluation des réserves minérales est un exercice complexe qui requiert une collaboration étroite entre les géologues, les ingénieurs miniers et les auditeurs. La comptabilisation des coûts d'exploration et de développement obéit à des règles strictes (norme IFRS 6 / SYSCOHADA) qui nécessitent un jugement professionnel éclairé.",
  "### Provisions pour réhabilitation",
  "Les sociétés minières ont l'obligation de constituer des provisions pour la réhabilitation des sites d'exploitation à la fin de leur vie. Le calcul de ces provisions repose sur des estimations techniques complexes (coût de réhabilitation, taux d'actualisation, durée d'exploitation) et fait l'objet d'un examen attentif des auditeurs.",
  "### Droits de douane et taxes minières",
  "Le Code minier de 2018 a introduit de nouvelles dispositions fiscales, notamment la suppression de la clause de stabilisation pour les nouveaux titres miniers. Les sociétés minières doivent désormais s'acquitter :",
  "- De la redevance minière (1% à 10% selon le minéral)\n- De l'impôt sur les profits (30%)\n- De la taxe sur les produits négociés\n- De la contribution au développement des communautés locales\n- Des droits de douane sur les importations d'équipements",
  img("L'exploitation minière en RDC génère des obligations comptables et fiscales spécifiques", "photo-1556742049-0cfed4f6a45d"),
  "## Les exigences ITIE",
  "La RDC est pays membre de l'ITIE depuis 2005. Les sociétés minières sont tenues de déclarer annuellement les paiements qu'elles effectuent aux autorités publiques (taxes, redevances, dividendes). Ces déclarations sont ensuite croisées avec les données publiées par l'État.",
  "> La conformité ITIE n'est pas optionnelle. Les entreprises qui ne respectent pas leurs obligations de déclaration s'exposent à des sanctions de l'ITIE et à une dégradation de leur réputation auprès des investisseurs internationaux.",
  "## Rôle du commissaire aux comptes",
  "Le commissaire aux comptes joue un rôle crucial dans le secteur minier. Au-delà de la certification des états financiers, il doit porter une attention particulière aux estimations comptables, aux provisions, aux engagements hors bilan et à la conformité réglementaire.",
  "## Notre expertise sectorielle",
  "Chez CAAF SAS, nous accompagnons plusieurs sociétés minières opérant dans le Lualaba et le Haut-Katanga. Notre équipe combine une expertise comptable de haut niveau et une connaissance approfondie des spécificités du secteur minier congolais.",
  "Nous intervenons sur l'ensemble du cycle d'audit : planification basée sur une évaluation des risques sectoriels, tests de contrôles adaptés aux processus miniers, travail sur les estimations et les provisions, et communication avec les parties prenantes.",
]

// ─── 6. Commissaire aux comptes OHADA ────────────────────
export const ARTICLE_CONTENT_CAC_OHADA: string[] = [
  "## Un rôle fondamental dans la gouvernance",
  "Le commissaire aux comptes (CAC) est une figure centrale de la gouvernance des sociétés commerciales dans l'espace OHADA. Sa mission de certification des comptes et de contrôle légal vise à garantir la fiabilité de l'information financière diffusée aux actionnaires, aux créanciers et aux tiers.",
  "Pourtant, de nombreuses entreprises congolaises méconnaissent les obligations légales en matière de nomination d'un CAC. Cet article propose un décryptage complet du cadre OHADA applicable.",
  img("La nomination du commissaire aux comptes est une obligation légale pour de nombreuses sociétés", "photo-1450101499163-c8848c66ca85"),
  "## Quelles sociétés doivent nommer un CAC ?",
  "L'Acte Uniforme OHADA relatif au droit des sociétés commerciales (AUSCGIE) impose la nomination d'un ou plusieurs commissaires aux comptes dans les cas suivants :",
  "- SA (Sociétés Anonymes) : nomination obligatoire, quelle que soit la taille\n- SARL dépassant les seuils fixés par l'Acte Uniforme\n- Sociétés faisant appel public à l'épargne\n- Sociétés contrôlées par une société anonyme\n- Sociétés d'assurance, banques et établissements financiers",
  "En dessous des seuils, la nomination d'un CAC peut être demandée par un ou plusieurs associés représentant au moins 10% du capital social.",
  "## Les critères de choix",
  "Le choix du commissaire aux comptes est une décision stratégique. Les critères suivants doivent être pris en compte :",
  "### Compétence et spécialisation",
  "Le CAC doit disposer des qualifications requises et d'une expérience pertinente dans le secteur d'activité de la société. Un CAC spécialisé dans le secteur minier ne sera pas nécessairement le plus adapté pour une société de télécommunications.",
  "### Indépendance",
  "L'indépendance est la condition sine qua non de l'exercice. Le CAC ne doit avoir aucun lien de nature à compromettre son objectivité avec la société, ses dirigeants ou ses actionnaires significatifs.",
  img("L'indépendance du CAC est la pierre angulaire de la mission", "photo-1589829545856-d10d557cf95f"),
  "### Continuité et rotation",
  "L'AUSCGIE prévoit des règles de rotation des CAC pour prévenir les risques liés à la familiarité excessive. Le mandat du CAC est limité dans le temps et ne peut être renouvelé indéfiniment.",
  "## La procédure de nomination",
  "La nomination du CAC intervient en assemblée générale ordinaire. La procédure comprend :",
  "- La proposition de candidature par le conseil d'administration ou les associés\n- L'évaluation de la candidature et vérification de l'éligibilité\n- Le vote en assemblée générale ordinaire\n- L'enregistrement de la nomination au registre du commerce\n- La publication de la nomination dans un journal d'annonces légales",
  "> Un CAC irrégulièrement nommé peut voir ses missions contestées. Il est impératif de respecter scrupuleusement la procédure légale pour garantir la validité de la nomination.",
  "## Les obligations du CAC",
  "Le commissaire aux comptes a pour missions principales :",
  "- Certifier la sincérité et la régularité des comptes annuels\n- Vérifier la conformité des comptes aux règles comptables applicables\n- Signaler au procureur de la République les faits délictueux dont il a connaissance\n- Présenter un rapport général aux actionnaires en assemblée\n- Surveiller la continuité d'exploitation",
  "## Notre engagement",
  "Chez CAAF SAS, nous exerçons des missions de commissariat aux comptes depuis plus de 25 ans. Notre approche combine rigueur technique, connaissance du terrain et dialogue constructif avec les directions.",
]

// ─── 7. TVA RDC ──────────────────────────────────────────
export const ARTICLE_CONTENT_TVA_RDC: string[] = [
  "## La TVA : un impôt simple en théorie, complexe en pratique",
  "La Taxe sur la Valeur Ajoutée (TVA) est l'un des impôts les plus importants en RDC. Son mécanisme semble simple à première vue — collecter la taxe sur les ventes et déduire celle payée sur les achats — mais la pratique révèle de nombreuses subtilités qui génèrent des erreurs coûteuses.",
  "Nos équipes interviennent régulièrement pour accompagner les entreprises dans la gestion de leur TVA. Voici les 7 erreurs les plus fréquentes que nous constatons sur le terrain.",
  img("La gestion de la TVA nécessite rigueur et vigilance au quotidien", "photo-1554224155-8d04cb21cd6c"),
  "## Erreur n°1 : La facturation incomplète",
  "Une facture non conforme est une facture qui ne permet pas la déduction de la TVA. Les mentions obligatoires sont strictes : numéro de RCCM, identifiant fiscal, numéro de facture séquentiel, date d'émission, désignation des biens ou services, prix unitaire HT, taux de TVA applicable, et montant TTC.",
  "De nombreuses entreprises — surtout les PME — émettent des factures ne respectant pas ces exigences. En cas de contrôle, ces factures sont rejetées et la TVA déduite correspondante est redressée.",
  "## Erreur n°2 : La déduction de TVA sur des dépenses non éligibles",
  "Toutes les dépenses n'ouvrent pas droit à déduction de TVA. Les principales exclusions sont :",
  "- Les dépenses de nature personnelle des dirigeants\n- Les véhicules de tourisme et leurs frais de fonctionnement\n- Les cadeaux d'affaires d'une valeur unitaire supérieure au seuil\n- Les dépenses somptuaires\n- Les opérations réalisées en dehors du territoire assujetti",
  "## Erreur n°3 : L'absence de rapprochement mensuel",
  "Chaque mois, le montant de TVA déclaré doit être rapproché avec les écritures comptables. Cette démarche, souvent négligée, permet de détecter les anomalies avant qu'elles ne se cumulent.",
  img("Le rapprochement mensuel des déclarations TVA est une pratique indispensable", "photo-1460925895917-afdab827c52f"),
  "## Erreur n°4 : La confusion entre taux de TVA",
  "La RDC applique un taux normal de 16% et des taux réduits pour certaines opérations. La confusion entre les taux est une source fréquente de redressement, notamment pour les entreprises opérant à la fois dans les zones urbaines et rurales.",
  "## Erreur n°5 : Le crédit de TVA non justifié",
  "Le crédit de TVA doit être justifié par des factures conformes, des bons de livraison et des bordereaux de paiement. Un crédit de TVA excessif par rapport au chiffre d'affaires déclaré est un signal d'alerte pour la DGI.",
  "> Un crédit de TVA supérieur à 20% du chiffre d'affaires trimestriel déclenche automatiquement un examen approfondi par la DGI. Veillez à ce que vos crédits soient toujours justifiables.",
  "## Erreur n°6 : Les retards de déclaration",
  "La TVA doit être déclarée et payée au plus tard le 15 du mois suivant la période d'imposition. Tout retard entraîne automatiquement l'application de pénalités : 10% du montant dû, plus 1,5% d'intérêts de retard par mois.",
  "## Erreur n°7 : La non-déclaration des opérations exonérées",
  "Même les opérations exonérées doivent être déclarées. L'omission de ces opérations dans les déclarations périodiques est une erreur courante qui peut entraîner des sanctions.",
  "## Nos recommandations",
  "Pour éviter ces pièges, nous recommandons la mise en place d'un processus rigoureux de gestion de la TVA :",
  "- Vérifier chaque facture entrante et sortante avant comptabilisation\n- Réaliser un rapprochement mensuel TVA / comptabilité\n- Conserver un dossier de crédit de TVA avec toutes les pièces justificatives\n- Mettre en place des alertes pour les dates de déclaration\n- Former régulièrement les équipes comptables aux évolutions réglementaires",
  img("Un processus rigoureux de gestion TVA protège l'entreprise contre les redressements", "photo-1552664730-d307ca884978"),
]

// ─── 8. COSO contrôle interne ────────────────────────────
export const ARTICLE_CONTENT_COSO: string[] = [
  "## Le cadre COSO : la référence mondiale",
  "Le Committee of Sponsoring Organizations of the Treadway Commission (COSO) a publié en 1992 un cadre de référence pour le contrôle interne qui est devenu la norme mondiale. En 2013, le cadre a été mis à jour pour intégrer les évolutions technologiques et les nouvelles formes de risques.",
  "En RDC, l'adoption du cadre COSO progresse, mais reste inégale. Les grandes entreprises minières et les banques l'ont largement intégré, tandis que les PME commencent seulement à s'y intéresser. Cet article présente trois retours d'expérience concrets d'implémentation.",
  img("L'implémentation du cadre COSO demande une approche structurée et méthodique", "photo-1497366811353-6870744d04b2"),
  "## Les cinq composantes du COSO",
  "Le cadre COSO repose sur cinq composantes interdépendantes :",
  "- **Environnement de contrôle** : l'intégrité et les valeurs éthiques, l'engagement de la direction, la structure organisationnelle\n- **Évaluation des risques** : l'identification et l'analyse des risques liés aux objectifs\n- **Activités de contrôle** : les politiques et procédures qui assurent la mise en œuvre des décisions\n- **Information et communication** : l'identification, la capture et l'échange d'informations\n- **Suivi** : l'évaluation de la qualité du système de contrôle interne au fil du temps",
  "## Cas n°1 : Une société minière du Lualaba",
  "Notre première mission concernait une société minière de taille moyenne exploitant un gisement de cuivre dans le Lualaba. L'entreprise connaissait des pertes récurrentes liées à des fraudes dans le processus d'approvisionnement.",
  "Nous avons commencé par un diagnostic complet des processus existants, identifiant 47 points de contrôle défaillants sur les 85 évalués. Les principales failles concernaient la séparation des fonctions (le même agent pouvait approuver une commande et valider la réception) et l'absence de procédure de rotation des fournisseurs.",
  img("Le secteur minier présente des risques de contrôle interne spécifiques", "photo-1504328345606-18bbc8c9d7d1"),
  "La mise en place du cadre COSO a permis de structurer un plan d'action de 12 mois, priorisant les risques les plus critiques. Résultat : une réduction de 60% des anomalies détectées et une économie estimée à 15% du budget approvisionnement.",
  "## Cas n°2 : Une banque commerciale de Kinshasa",
  "La deuxième mission concernait une banque commerciale souhaitant renforcer son dispositif de contrôle interne suite aux nouvelles exigences de la BCC. Le principal défi résidait dans l'intégration du cadre COSO avec le cadre prudentiel Bâle III.",
  "Nous avons développé une matrice de risques spécifique au secteur bancaire congolais, intégrant les risques opérationnels, de crédit, de marché et de conformité. Chaque risque a été cartographié avec ses contrôles associés et un indicateur de performance.",
  "> L'intégration du COSO dans le secteur bancaire requiert une adaptation spécifique. Les composantes du cadre doivent être articulées avec les exigences de Bâle III et les directives de la BCC.",
  "## Cas n°3 : Une PME industrielle",
  "Le troisième cas illustre l'adaptation du cadre COSO aux réalités d'une PME. L'entreprise, un fabricant de matériaux de construction employant 120 personnes, souhaitait structurer son contrôle interne pour préparer sa première nomination d'un commissaire aux comptes.",
  "Pour cette mission, nous avons adopté une approche simplifiée, focalisée sur les 17 principes fondamentaux du COSO 2013. L'objectif n'était pas de mettre en place un dispositif sophistiqué mais de créer les bases d'un contrôle interne fonctionnel et évolutif.",
  "## Les facteurs clés de succès",
  "Nos trois missions nous ont permis d'identifier les facteurs clés de succès d'une implémentation COSO en RDC :",
  "- L'engagement total de la direction générale\n- La nomination d'un responsable du contrôle interne dédié\n- Une communication régulière sur les objectifs et les progrès\n- Une formation continue des équipes opérationnelles\n- Un suivi trimestriel des plans d'action avec des indicateurs mesurables\n- Un dialogue constructif avec le commissaire aux comptes",
  img("L'engagement de la direction est le facteur n°1 de réussite", "photo-1552664730-d307ca884978"),
]

// ─── 9. BCC audit banques ────────────────────────────────
export const ARTICLE_CONTENT_BCC: string[] = [
  "## Un cadre prudentiel en pleine évolution",
  "La Banque Centrale du Congo (BCC) a renforcé considérablement ses exigences en matière de supervision bancaire au cours des dernières années. Les nouvelles directives, alignées sur les standards de Bâle III, imposent aux établissements de crédit des obligations accrues en matière de fonds propres, de liquidité et de gestion des risques.",
  "Pour les commissaires aux comptes des banques, ces évolutions représentent un défi majeur. La mission de certification doit désormais intégrer un examen approfondi de la conformité prudentielle, au-delà de la simple vérification des états financiers.",
  img("Le secteur bancaire congolais fait face à des exigences prudentielles de plus en plus strictes", "photo-1541354329998-f4d9a9f9297f"),
  "## Les principales exigences de la BCC",
  "### Ratios de solvabilité",
  "Les banques doivent maintenir des ratios de fonds propres minimums calculés conformément aux directives de la BCC. Le ratio de capital de base (Tier 1) et le ratio de capital total sont surveillés trimestriellement.",
  "- Ratio de capital de base minimum : 8%\n- Ratio de capital total minimum : 10%\n- Coussin de conservation : 2,5%\n- Coussin contracyclique : variable selon la conjoncture",
  "### Ratios de liquidité",
  "L'introduction du ratio de couverture de liquidité (LCR) et du ratio de financement stable net (NSFR) oblige les banques à revoir la structure de leur bilan et à maintenir des réserves de liquidité suffisantes.",
  "### Normes de reporting",
  "La BCC impose désormais des rapports prudentiels mensuels, trimestriels et annuels, avec des exigences de détail significativement plus importantes qu'auparavant.",
  img("Les banques doivent investir dans des systèmes de reporting performants", "photo-1486406146926-c627a92ad1ab"),
  "## L'impact sur la mission du CAC",
  "Le commissaire aux comptes d'une banque doit désormais :",
  "- Vérifier le calcul des ratios prudentiels\n- Évaluer les modèles internes de mesure des risques\n- Examiner les provisions pour pertes de crédit attendues (IFRS 9)\n- Contrôler la conformité des informations prudentielles publiées\n- Tester l'efficacité du dispositif de gestion des risques",
  "> La BCC attend du commissaire aux comptes qu'il ne se limite pas à une vérification comptable. Sa mission doit couvrir l'ensemble du dispositif prudentiel de la banque.",
  "## Les défis spécifiques en RDC",
  "L'audit des banques en RDC présente des défis spécifiques liés au contexte :",
  "- La qualité variable des systèmes d'information bancaires\n- La complexité des opérations en devise dans un environnement de change volatile\n- L'identification des parties liées et des opérations avec les actionnaires\n- La gestion des actifs immobilisés dans un contexte d'inflation\n- La conformité aux sanctions internationales et à la lutte anti-blanchiment",
  "## Les risques de non-conformité",
  "Les banques qui ne respectent pas les exigences prudentielles s'exposent à des sanctions graduelles de la BCC : avertissement, limitation des distributions, injonction de renforcement des fonds propres, et dans les cas les plus graves, retrait d'agrément.",
  "Pour le commissaire aux comptes, l'enjeu est également réputationnel. La signature d'un rapport de certification sans réserve sur des comptes qui ne respectent pas les normes prudentielles engage sa responsabilité professionnelle.",
  img("La conformité prudentielle est devenue un enjeu stratégique majeur pour les banques congolaises", "photo-1590283603385-17ffb3a7f29f"),
  "## Notre accompagnement",
  "CAAF SAS accompagne plusieurs établissements bancaires en RDC dans leurs obligations de certification et de conformité prudentielle. Notre équipe combine expertise comptable, connaissance du cadre réglementaire BCC et expérience sectorielle.",
]

// ─── 10. CAAF 30 ans ─────────────────────────────────────
export const ARTICLE_CONTENT_CAAF_30ANS: string[] = [
  "## Trois décennies d'engagement",
  "En 2024, CAAF SAS célèbre 30 années d'existence. Trois décennies au cours desquelles le cabinet s'est imposé comme un acteur incontournable de l'expertise comptable et de l'audit en République Démocratique du Congo.",
  "Fondé en 1994 par un groupe d'experts-comptables visionnaires, le cabinet avait pour ambition initiale d'apporter aux entreprises congolaises un niveau de service comparable aux standards internationaux. Trente ans plus tard, cette ambition reste le moteur de chaque intervention.",
  img("Les locaux du cabinet CAAF SAS au cœur de Kinshasa", "photo-1497366811353-6870744d04b2"),
  "## Les origines : 1994-2004",
  "Les premières années du cabinet ont été marquées par un contexte national difficile. En dépit des défis économiques et politiques, l'équipe fondatrice a su bâtir une clientèle fidèle composée d'entreprises locales et de partenaires internationaux.",
  "Les premières missions concernaient principalement l'audit financier et le commissariat aux comptes. Très vite, les fondateurs ont identifié le besoin d'un accompagnement plus large, incluant le conseil fiscal et l'assistance comptable.",
  "> Notre plus grande fierté n'est pas d'avoir survécu à ces années difficiles, mais d'avoir maintenu un niveau d'exigence constant depuis le premier jour. La rigueur n'a pas de prix, mais elle a un coût — celui de la constance.",
  "## La croissance : 2004-2014",
  "La deuxième décennie a été celle de la structuration et de la croissance. Le cabinet a ouvert son deuxième bureau à Lubumbashi, recruté de nouveaux talents et développé de nouvelles lignes de service : due diligence, conseil fiscal, advisory stratégique.",
  "Cette période a également été marquée par la montée en puissance du secteur minier en RDC. CAAF SAS a accompagné plusieurs sociétés minières dans leurs obligations de certification, de conformité ITIE et de reporting à leurs maisons-mères.",
  img("L'équipe CASF SAS a grandi pour atteindre plus de 40 professionnels", "photo-1552664730-d307ca884978"),
  "## La maturité : 2014-2024",
  "La troisième décennie a confirmé la position de CAAF SAS comme cabinet de référence. Le cabinet a accompagné des opérations majeures : fusions-acquisitions, introductions en bourse, restructurations de groupes industriels.",
  "L'équipe comptabilise désormais plus de 40 professionnels, incluant des associés, des directeurs, des managers et des collaborateurs seniors. Chaque membre de l'équipe partage les mêmes valeurs : intégrité, excellence, discrétion et engagement.",
  "## Quelques chiffres clés",
  "- Plus de 300 missions réalisées en 30 ans\n- Plus de 80 clients actifs dans 12 secteurs d'activité\n- 2 bureaux : Kinshasa et Lubumbashi\n- Plus de 40 professionnels dédiés\n- 100% des missions livrées dans les délais convenus",
  img("Les 30 ans de CAAF SAS sont le fruit d'un engagement collectif", "photo-1573164713988-8665fc963095"),
  "## Vision pour l'avenir",
  "Les 30 prochaines années s'annoncent porteuses de transformations majeures : digitalisation des processus comptables, adoption des normes IFRS, montée en puissance de la cybersécurité, évolution du cadre OHADA.",
  "CAAF SAS est résolument tourné vers l'avenir. Notre ambition : accompagner la nouvelle génération d'entreprises congolaises dans leur croissance, tout en préservant les valeurs fondatrices qui ont fait notre réputation.",
  "> 30 ans, ce n'est pas une fin — c'est un nouveau départ. Nous sommes prêts pour les 30 prochaines années.",
]

// ─── 11. Cybersécurité ────────────────────────────────────
export const ARTICLE_CONTENT_CYBERSECURITE: string[] = [
  "## La menace est réelle",
  "Les cyberattaques ne sont plus une menace théorique pour les entreprises congolaises — elles sont une réalité quotidienne. Selon les estimations, le nombre d'attaques ciblant les entreprises africaines a été multiplié par cinq au cours des trois dernières années. Et la RDC n'est pas épargnée.",
  "Ransomwares, phishing, compromission de comptes de messagerie, vol de données client : les vecteurs d'attaque se multiplient et se sophistiquent. Les entreprises qui n'investissent pas dans la protection de leurs systèmes d'information s'exposent à des conséquences potentiellement dévastatrices.",
  img("La protection des systèmes d'information est devenue un enjeu stratégique", "photo-1558494949-ef010cbdcc31"),
  "## L'audit IT : un impératif de gouvernance",
  "L'audit informatique — ou audit IT — est devenu un outil indispensable de gouvernance d'entreprise. Il ne s'agit plus d'un luxe technologique réservé aux grandes multinationales, mais d'une nécessité pour toute organisation qui traite des données sensibles ou qui dépend de ses systèmes d'information pour fonctionner.",
  "L'audit IT couvre plusieurs dimensions :",
  "- La sécurité des systèmes et des réseaux\n- La gestion des accès et des identités\n- La continuité d'activité et la reprise après sinistre\n- La protection des données personnelles\n- La gouvernance des projets IT\n- La conformité aux réglementations applicables",
  "## Le cadre COBIT",
  "COBIT (Control Objectives for Information and Related Technologies) est le cadre de référence pour la gouvernance et le management des technologies de l'information. Développé par l'ISACA, il fournit un ensemble de bonnes pratiques pour aligner la stratégie IT sur les objectifs de l'entreprise.",
  "L'implémentation de COBIT en RDC reste limitée, mais les entreprises qui l'adoptent constatent des améliorations significatives dans la gestion de leurs risques IT.",
  img("Le cadre COBIT offre une approche structurée de la gouvernance IT", "photo-1518770660439-4636190af475"),
  "## Les risques spécifiques en RDC",
  "Les entreprises congolaises font face à des risques IT spécifiques liés au contexte local :",
  "- Infrastructure réseau de qualité variable\n- Pannes d'électricité fréquentes affectant la continuité des systèmes\n- Manque de personnel IT qualifié\n- Faible sensibilisation des utilisateurs aux risques cyber\n- Absence de cadre réglementaire spécifique sur la protection des données\n- Utilisation de logiciels non licenciés exposant à des vulnérabilités",
  "## Les 5 mesures prioritaires",
  "Pour les entreprises qui souhaitent renforcer leur posture de sécurité, voici les cinq mesures prioritaires recommandées par nos équipes :",
  "### 1. Inventaire des actifs IT",
  "On ne peut pas protéger ce qu'on ne connaît pas. La première étape consiste à recenser l'ensemble des actifs informatiques : serveurs, postes de travail, logiciels, bases de données, comptes utilisateurs.",
  "### 2. Gestion des accès",
  "La majorité des incidents de sécurité implique une compromission des comptes d'accès. La mise en place de politiques strictes de gestion des mots de passe, l'authentification à deux facteurs et la revue régulière des droits d'accès sont essentielles.",
  img("La sensibilisation des utilisateurs est la première ligne de défense", "photo-1553729459-afe8f2e2ed58"),
  "### 3. Sauvegarde et reprise",
  "Un plan de sauvegarde régulier et testé est la meilleure protection contre les ransomwares. Les sauvegardes doivent être stockées hors ligne et testées régulièrement pour garantir leur restauration.",
  "### 4. Sensibilisation des utilisateurs",
  "La formation régulière des employés aux bonnes pratiques de sécurité (reconnaissance de phishing, gestion des mots de passe, signalement d'incidents) est souvent le maillon le plus faible de la chaîne.",
  "### 5. Audit de sécurité annuel",
  "Un audit de sécurité annuel, réalisé par un cabinet spécialisé, permet d'identifier les vulnérabilités et de prioriser les investissements en sécurité.",
  "> La cybersécurité n'est pas un coût — c'est un investissement. Le coût d'un audit annuel est dérisoire comparé au coût d'une attaque réussie : interruption d'activité, perte de données, atteinte à la réputation.",
  "## Notre offre d'audit IT",
  "CAAF SAS propose des missions d'audit informatique adaptées aux réalités des entreprises congolaises. Notre approche combine l'expertise du cadre COBIT avec une connaissance approfondie du contexte technologique local.",
]

// ─── 12. OHADA Acte Uniforme ─────────────────────────────
export const ARTICLE_CONTENT_OHADA_ACTE_UNIFORME: string[] = [
  "## Au-delà du commissariat aux comptes",
  "Quand on évoque l'OHADA dans le contexte des entreprises congolaises, l'attention se porte généralement sur l'obligation de nommer un commissaire aux comptes. Or, l'Acte Uniforme relatif au Droit des Sociétés Commerciales (AUSCGIE) impose de nombreuses autres obligations qui sont souvent ignorées — à vos risques et périls.",
  "Cet article propose une revue des dispositions les plus fréquemment négligées par les sociétés commerciales établies en RDC.",
  img("L'Acte Uniforme OHADA encadre strictement la vie des sociétés commerciales", "photo-1589829545856-d10d557cf95f"),
  "## Les obligations de fonctionnement",
  "### Tenue d'une comptabilité régulière",
  "L'AUSCGIE impose à toute société commerciale de tenir une comptabilité conforme au SYSCOHADA. Cette obligation ne se limite pas aux sociétés assujetties au commissariat aux comptes — elle concerne toutes les sociétés immatriculées au registre du commerce.",
  "### Approbation des comptes annuels",
  "Les comptes annuels doivent être approuvés par les associés ou actionnaires dans les six mois de la clôture de l'exercice. Ce délai est fréquemment dépassé, exposant les dirigeants à des sanctions.",
  "- Établissement des comptes annuels dans les 3 mois\n- Communication aux commissaires aux comptes (le cas échéant)\n- Établissement du rapport de gestion dans les 3 mois\n- Convocation de l'assemblée générale dans les 6 mois\n- Dépôt des comptes au greffe dans le mois suivant l'approbation",
  "### Information des associés",
  "Les associés disposent de droits d'information étendus : droit de communication des documents sociaux, droit de poser des questions écrites au dirigeant, droit de demander une expertise de gestion.",
  "## Les obligations en cas de difficultés",
  "### Déclaration de cessation des paiements",
  "Le dirigeant d'une société en cessation des paiements a l'obligation de déclarer cette situation au tribunal dans les 30 jours. Le défaut de déclaration est constitutif d'une faute de gestion pouvant engager la responsabilité personnelle du dirigeant.",
  img("Les obligations légales des dirigeants sont strictes et leur méconnaissance est risquée", "photo-1450101499163-c8848c66ca85"),
  "> De nombreux dirigeants congolaises ignorent que le simple fait de ne pas déclarer la cessation des paiements dans les délais constitue une faute de gestion susceptible d'entraîner une condamnation personnelle.",
  "### Dissolution anticipée",
  "L'AUSCGIE prévoit des cas de dissolution anticipée obligatoire, notamment la perte de la moitié du capital social. Cette situation, courante dans un environnement économique volatile, oblige les dirigeants à convoquer une assemblée extraordinaire pour statuer sur la dissolution ou le maintien de la société.",
  "## Les obligations de publication",
  "### Registre du Commerce et du Crédit Mobilier (RCCM)",
  "Toute société commerciale doit être immatriculée au RCCM et mettre à jour ses informations en cas de modification statutaire (changement de siège, d'objet social, de dirigeants, d'associés).",
  "### Annonces légales",
  "Certaines décisions doivent faire l'objet d'une publication dans un journal d'annonces légales : constitution de la société, modification des statuts, nomination de CAC, dissolution, liquidation.",
  "## Les sanctions en cas de manquement",
  "L'AUSCGIE prévoit des sanctions pour les dirigeants qui ne respectent pas leurs obligations :",
  "- Sanctions pénales pour tenue d'une comptabilité irrégulière\n- Responsabilité personnelle pour absence de déclaration de cessation des paiements\n- Nullité des décisions prises en violation des procédures légales\n- Exclusion de la gestion pour faute de gestion caractérisée",
  img("La conformité OHADA n'est pas optionnelle — c'est une obligation légale", "photo-1521791136064-7986c2920216"),
  "## Notre recommandation",
  "Nous recommandons à tout dirigeant de société commerciale en RDC de faire un état des lieux de sa conformité OHADA. Ce diagnostic, relativement simple à réaliser, peut éviter des complications juridiques et financières considérables.",
  "> Chez CAAF SAS, nous proposons des missions de diagnostic de conformité OHADA qui couvrent l'ensemble des obligations légales de votre société. Un investissement minimal pour une sécurité juridique maximale.",
]

// ═══════════════════════════════════════════════════════════
// MAPPING
// ═══════════════════════════════════════════════════════════

export const ARTICLE_CONTENTS: Record<string, string[]> = {
  "syscohada-revise-2024-ce-qui-change": ARTICLE_CONTENT_SYSCOHADA,
  "controle-fiscal-rdc-2024-comment-se-preparer": ARTICLE_CONTENT_CONTROLE_FISCAL,
  "audit-interne-externalise-avantages-pme": ARTICLE_CONTENT_AUDIT_INTERNE,
  "prix-de-transfert-rdc-guide-pratique": ARTICLE_CONTENT_PRIX_TRANSFERT,
  "secteur-minier-rdc-enjeux-audit-2024": ARTICLE_CONTENT_SECTEUR_MINIER,
  "commissaire-aux-comptes-nomination-ohada": ARTICLE_CONTENT_CAC_OHADA,
  "tva-rdc-erreurs-frequentes": ARTICLE_CONTENT_TVA_RDC,
  "controle-interne-coso-implementation-rdc": ARTICLE_CONTENT_COSO,
  "banque-bcc-audit-exigences-2024": ARTICLE_CONTENT_BCC,
  "caaf-30-ans-expertise": ARTICLE_CONTENT_CAAF_30ANS,
  "audit-informatique-cybersecurite-rdc": ARTICLE_CONTENT_CYBERSECURITE,
  "ohada-acte-uniforme-societes-commerciales": ARTICLE_CONTENT_OHADA_ACTE_UNIFORME,
}

// Default content for articles without specific content
export const DEFAULT_ARTICLE_CONTENT: string[] = [
  "## Introduction",
  "Cet article est en cours de rédaction par nos experts. Le contenu complet sera disponible prochainement.",
  "> Abonnez-vous à notre newsletter pour être informé de la publication.",
  "## En attendant",
  "N'hésitez pas à nous contacter directement si vous avez des questions sur ce sujet. Nos associés et managers sont disponibles pour un échange personnalisé.",
  "- Contactez-nous par email : contact@caaf-rdc.com\n- Appelez-nous : +243 XX XXX XXXX\n- Prenez rendez-vous en ligne",
]
